parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    mailer_user: jerome.roessler@gmail.com

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: \App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"