vich_uploader:
    db_driver: orm

    mappings:
        previews:
            uri_prefix: /uploads/previews
            upload_destination: '%kernel.project_dir%/public/uploads/previews'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true