<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'KevinPapst\AdminLTEBundle\Menu\MenuBuilder' shared service.

include_once $this->targetDirs[3].'/vendor/kevinpapst/adminlte-bundle/Menu/MenuBuilder.php';

return $this->privates['KevinPapst\AdminLTEBundle\Menu\MenuBuilder'] = new \KevinPapst\AdminLTEBundle\Menu\MenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
