<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK571D3K\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK571D3K/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK571D3K.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK571D3K\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerK571D3K\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'K571D3K',
    'container.build_id' => 'b6d2a8c3',
    'container.build_time' => 1539875506,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK571D3K');
