<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUHYf4P\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUHYf4P/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJUHYf4P.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJUHYf4P\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJUHYf4P\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JUHYf4P',
    'container.build_id' => 'ca0644e2',
    'container.build_time' => 1539960771,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUHYf4P');
