<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOPAqVgl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOPAqVgl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOPAqVgl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOPAqVgl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOPAqVgl\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OPAqVgl',
    'container.build_id' => '4e1e45c3',
    'container.build_time' => 1540052652,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOPAqVgl');
